

INSERT INTO PERSON 
(ID,NAME,LOCATION,BIRTH_DATE)
VALUES
(10001,'FANNY','PARAISO',sysdate());


INSERT INTO PERSON 
(ID,NAME,LOCATION,BIRTH_DATE)
VALUES
(10002,'OMAR','SOL',sysdate());


INSERT INTO PERSON 
(ID,NAME,LOCATION,BIRTH_DATE)
VALUES
(10003,'JULIO','SELVA',sysdate());

